#!/bin/sh
gst-launch-1.0 -v udpsrc port=5801 ! \
"application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, payload=(int)96" ! \
rtph264depay ! \
h264parse ! \
omxh264dec ! \
nvvidconv ! \
xvimagesink -e
#nvegltransform ! nveglglessink "window-width=320" "window-height=240" -e
