#!/bin/sh

# Search for the next unused video file name:
index=0
file_name=video-0000.mp4

printf 'Have index %d\n' "$index"

while [ -e $file_name ]
do
    index=$(( $index + 1 ))
    file_name=$( printf 'video1-%04d.mp4' "$index" )
    printf 'Checking %d - %s\n' "$index" "$file_name"
done

printf 'Transmitting Video To Host %s\n' "$1"
printf 'Saving to File %s\n' "$file_name"

gst-launch-1.0 -e nvarguscamerasrc do-timestamp=true ! \
'video/x-raw(memory:NVMM),format=(string)NV12, width=(int)1280, height=(int)720, framerate=60/1' ! \
nvvidconv flip-method=0 ! \
'video/x-raw(memory:NVMM), width=(int)640, height=(int)360, format=(string)I420' ! tee name=t ! \
queue ! omxh264enc control-rate=2 bitrate=450000 profile=1 preset-level=1 ! \
'video/x-h264, framerate=60/1, stream-format=(string)byte-stream'! h264parse !\
rtph264pay config-interval=1 ! udpsink host=$1 port=5801 t. ! \
queue ! omxh264enc control-rate=2 bitrate=600000 profile=1 preset-level=1 ! \
'video/x-h264, framerate=60/1, stream-format=(string)byte-stream' \
! h264parse ! qtmux ! filesink location=$file_name
