#!/bin/sh
echo Transmitting Video To Host $1

gst-launch-1.0 -v nvarguscamerasrc do-timestamp=true ! \
'video/x-raw(memory:NVMM),format=(string)NV12, width=(int)1280, height=(int)720, framerate=60/1' ! \
nvvidconv flip-method=0 ! \
'video/x-raw(memory:NVMM), width=(int)640, height=(int)360, format=(string)NV12' ! videorate drop-only=true max-rate=30 ! \
'video/x-raw(memory:NVMM), width=(int)640, height=(int)360, format=(string)NV12, framerate=30/1' ! \
omxh264enc control-rate=2 bitrate=400000 profile=1 preset-level=1 ! \
'video/x-h264, framerate=30/1, stream-format=(string)byte-stream' ! \
h264parse ! rtph264pay config-interval=1 mtu=1000 ! udpsink host=$1 port=5801
