#!/bin/sh
echo Transmitting $1 Video To Host $2

gst-launch-1.0 -vv v4l2src device=$1 ! \
'video/x-raw,format=(string)YUY2, width=(int)320, height=(int)240, framerate=30/1' ! \
nvvidconv flip-method=0 ! \
'video/x-raw(memory:NVMM),width=(int)320,height=(int)240,format=(string)NV12' ! \
omxh264enc control-rate=2 bitrate=500000 profile=1 preset-level=1 ! \
'video/x-h264, framerate=30/1, stream-format=(string)byte-stream' ! \
h264parse ! rtph264pay config-interval=1 ! udpsink host=$2 port=5801
