#!/bin/sh

# Search for the next unused video file name:
index=0
file_name=video2-0000.mp4

printf 'Have index %d\n' "$index"

while [ -e $file_name ]
do
    index=$(( $index + 1 ))
    file_name=$( printf 'video2-%04d.mp4' "$index" )
    printf 'Checking %d - %s\n' "$index" "$file_name"
done

printf 'Transmitting Video %s To Host %s\n' "$1" "$2"
printf 'Saving to File %s\n' "$file_name"

gst-launch-1.0 -e v4l2src device=$1 ! \
'video/x-raw,format=(string)YUY2, width=(int)320, height=(int)240, framerate=30/1' ! \
nvvidconv flip-method=0 ! \
'video/x-raw(memory:NVMM),width=(int)320,height=(int)240,format=(string)NV12' ! \
tee name=t ! \
queue ! omxh264enc control-rate=2 bitrate=400000 profile=1 preset-level=1 ! \
'video/x-h264, framerate=30/1, stream-format=(string)byte-stream'! h264parse !\
rtph264pay config-interval=1 ! udpsink host=$2 port=5801 t. ! \
queue ! omxh264enc control-rate=2 bitrate=600000 profile=1 preset-level=1 ! \
'video/x-h264, framerate=30/1, stream-format=(string)byte-stream' \
! h264parse ! qtmux ! filesink location=$file_name
